name: Update Code Nodes

on:
  push:
    branches:
      - main
    paths:
      - 'codenodes/*.py'

jobs:
  update-nodes:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3.5.3
    
    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.11'
    
    - name: Verify Python files
      run: |
        for file in CodeNodes/*.py; do
          python -m py_compile "$file" || exit 1
        done
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install requests
        fi
    
    - name: Update Code Nodes
      env:
        TAKTILE_API_KEY: ${{ secrets.TAKTILE_API_KEY }}
      run: |
        if ! python update_code_nodes.py; then
          echo "::error::Failed to update Code Nodes"
          exit 1
        fi
        echo "::notice::Successfully updated Code Nodes"
